- project:
    templates:
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - check-requirements
    check:
      jobs:
        - openstack-tox-functional
    gate:
      jobs:
        - openstack-tox-functional
